### ISSUE TITLE
Just put my website online and for some reason the mobile version does not work in the CSS

### ISSUE THREAD

**Issue by akselsalmi** [akselsalmi/webdesigntemplate#2]
Help!! 
I just put my repo online, and after viewing it on my phone the css was totally messed up!!! I was really planning on showing this to my friends today but this issue really doesn't make it look good!

Please help, and thank you in advance!
(I've heard the hacktoberfest label is a good way to get people to fix issues)

**Comment by yashkhandelwal2203** [comment]
hey, i would like to accept this issue.

**Comment by Purple-Hacker** [comment]
It is trying to use the CSS and shrink it down to display on your phone, you need to have arguements that rescale things for your phone. I will make a PR now and it should hopefully fix it, please let me know if it does!
